### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by salk52** [TrackableEntities/TrackableEntities.Core.Sample#10]
Hi

Do you plan Blazor Wasm example as a client? 
I tired to make it work with existing code but with no success.

**Comment by tonysneed** [comment]
Cool idea. Can you tel me a bit more about the trouble you’re running into?

**Comment by salk52** [comment]
Well, currently newtonsoft json does not work on Blazor Wasm. Instead you need to use System.Net.Http.Json

**Comment by tonysneed** [comment]
@salk52 Looks like this would entail a change to [trackable-entities/Source/TrackableEntities.Client](https://github.com/TrackableEntities/trackable-entities/tree/develop/Source/TrackableEntities.Client). Care to submit a PR?

**Comment by tonysneed** [comment]
Closing for now. Please re-open if needed.
