### ISSUE TITLE
System.ComponentModel.DataAnnotations Assembly Reference

### ISSUE THREAD

**Issue by ganagus** [TrackableEntities/TrackableEntities.Core.Sample#3]
In NetCoreSample.Entities project, there is an assembly reference to System.ComponentModel.DataAnnotations. It seems that I couldn't find the assembly on my local computer. So, I deleted it and then replaced with [System.ComponentModel.Annotations NuGet package](https://www.nuget.org/packages/System.ComponentModel.Annotations/). Then, I built the solution and succeed.

My question: is there any specific reason to use assembly reference instead of using NuGet package? If using NuGet package is ok, wouldn't it be better to use NuGet package instead of assembly reference?

Thanks.

**Comment by tonysneed** [comment]
I think using the NuGet package is preferred.
