### ISSUE TITLE
Error while running sample application

### ISSUE THREAD

**Issue by noufionline** [TrackableEntities/TrackableEntities.Core.Sample#6]
When trying to load a particular order for a customer getting the following error.

`System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NetCoreSample.ConsoleClient.Program.GetCustomerOrders(HttpClient client, String customerId, MediaTypeFormatter formatter) in C:\Users\Noufal\Downloads\TrackableEntities.Core.Sample-master\NetCoreSample.ConsoleClient\Program.cs:line 146
   at NetCoreSample.ConsoleClient.Program.Main(String[] args) in C:\Users\Noufal\Downloads\TrackableEntities.Core.Sample-master\NetCoreSample.ConsoleClient\Program.cs:line 45

Inner Exception 1:
JsonReaderException: The reader's MaxDepth of 256 has been exceeded. Path '$values[0].customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[1].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[1].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[1].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[1].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[1].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[0].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[2].order.customer.orders.$values[1].orderDetails.$values[2].product.orderDetails.$values[1].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[2].order.customer.orders.$values[0].orderDetails.$values[1].product.orderDetails.$values[1].order.customer.orders.$values[1].orderDetails.$values[1].product.orderDetails.$values[0].order.customer.orders.$values[1].orderDetails.$values[0].product.orderDetails.$values[1].order.customer.orders.$values[0].orderDetails.$values[0].product.orderDetails.$values[4].order.customer.orders.$values[1].orderDetails.$values[2].product.orderDetails.$values[0].order.orderDetails.$values[1].product.orderDetails.$values[2].order.customer.orders.$values[1].orderDetails.$values', line 1, position 26526.
`

**Comment by tonysneed** [comment]
Noted!
