### ISSUE TITLE
Asp.Net MVC/Razor Sample

### ISSUE THREAD

**Issue by M0Bilal** [TrackableEntities/TrackableEntities.Core.Sample#7]
Can someone please post a sample of this library that can demonstrate how to track changes on an Asp.Net web client e.g. MVC or Razor Pages? Or can someone guide how to achieve this?
The sample is not sufficient enough for realtime problems in the web.

**Comment by tonysneed** [comment]
Some preliminary work was done on a JavaScript client for Trackable Entities. But it would entail a great deal more work to complete and interest is not sufficient to warrant.
